import * as hz from "horizon/core";
import * as ui from "horizon/ui";
export declare class triviaDisplay extends ui.UIComponent<typeof triviaDisplay> {
    protected panelHeight: number;
    protected panelWidth: number;
    static s_instance: triviaDisplay;
    static propsDefinition: {};
    private bindQuestion;
    private bindAnswerA;
    private bindAnswerB;
    private bindAnswerC;
    private bindAnswerD;
    private bindTimer;
    private bindRounddigit1;
    private bindRounddigit2;
    private bindRoundopacity1;
    private bindRoundopacity2;
    private binddigit1;
    private binddigit2;
    private bindopacity1;
    private bindopacity2;
    private iterator;
    private answers;
    private correctAnswer;
    private correctAnswerID;
    private selectedCategoryID;
    private selectedCategoryDB;
    private categoryImage;
    private pagesbinding;
    private isPlaying;
    private percentageBindings;
    private barHeights;
    private roundOriginalAnswer;
    private lineColors;
    private answerLabels;
    private roundNumber;
    private roundQuestionsQTY;
    private roundNumberValue;
    preStart(): void;
    processAnswer(player: hz.Player, answerID: number): void;
    private calculateStats;
    allplayersEliminated(): void;
    private countdown;
    private countdownUpdateDisplay;
    private switchPages;
    private number2Image;
    private setRoundNumber;
    startGame(winningCategory: number, players: Map<hz.Player, boolean>): void;
    displayQuestion(): void;
    initializeUI(): ui.UINode;
}
